export { ToastProvider } from './ToastProvider'
export { ErrorBoundary } from './ErrorBoundary'
export { InteractiveGuidance } from './InteractiveGuidance'
export { MilestoneTracker } from './MilestoneTracker'
export { Breadcrumbs } from './Breadcrumbs'
export { SectionProgress } from './SectionProgress'
export { ContentSuggestions } from './ContentSuggestions'
export { ProgressiveDisclosure } from './ProgressiveDisclosure'
export { UnifiedDashboard } from './UnifiedDashboard'
export { UnifiedFAB } from './UnifiedFAB'
export { ThemeToggle } from './ThemeToggle'

// Legacy exports for backward compatibility (deprecated)
export { ExplorationDashboard } from './ExplorationDashboard'
export { ExplorationFAB } from './ExplorationFAB'
